version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
      day: monday
    groups:
      beroenden:
        patterns: ["*"]
    labels: ["beroenden"]
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
    labels: ["beroenden"]
